/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.CtrlConcepto;
import Controller.CtrlFormaPago;
import Controller.CtrlTercero;
import Theme.Paleta;
import Theme.Theme;
import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.JOptionPane;

/**
 *
 * @author lmog2
 */
public class FrmConcepto extends javax.swing.JPanel {

    private CtrlConcepto controlador;

    public FrmConcepto() {
        initComponents();
        panelMain.putClientProperty(FlatClientProperties.STYLE, Theme.getPanel());
        interfaz();
    }

    public void setControlador(CtrlConcepto controlador) {
        this.controlador = controlador;
    }

    public void interfaz() {

        tit1.putClientProperty(FlatClientProperties.STYLE, Theme.h1);
        titDatos.putClientProperty(FlatClientProperties.STYLE, Theme.h2);
        panelTitulo.putClientProperty(FlatClientProperties.STYLE, Theme.Headerpanel);
        panelDatos.putClientProperty(FlatClientProperties.STYLE, Theme.Headerpanel);
        // Estiliza la tabla
        // Estilo general de la tabla
        tableConcepto.putClientProperty(FlatClientProperties.STYLE,
                "showHorizontalLines:true;"
                + "showVerticalLines:false;"
                + "rowHeight:40;"
                + "intercellSpacing:10,5");

        // Estilo del encabezado de la tabla
        tableConcepto.getTableHeader().putClientProperty(FlatClientProperties.STYLE,
                "hoverBackground:" + "lighten(" + Paleta.getbColorPanel() + ",4%);"
                + "height:40;"
                + "separatorColor:$TableHeader.background;"
                + "font:bold $h4.font");
        lbl1.putClientProperty(FlatClientProperties.STYLE, Theme.h3);

        lbl9.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        lbl10.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        txtId.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        cmbEstado.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        txtDescrip.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        btn.putClientProperty(FlatClientProperties.STYLE, Theme.btnPrinci + ";" + Theme.h2);
        btnEliminar.putClientProperty(FlatClientProperties.STYLE, Theme.btnTer + ";" + Theme.h2);
        btnEliminar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        tit1 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tableConcepto = new javax.swing.JTable();
        panelDatos = new javax.swing.JPanel();
        titDatos = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        txtDescrip = new javax.swing.JTextField();
        lbl9 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lbl10 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();

        panelMain.setBackground(new java.awt.Color(204, 204, 255));

        panelTitulo.setBackground(new java.awt.Color(153, 153, 255));

        tit1.setText("Gestion de terceros");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tit1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        tableConcepto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripcion", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableConcepto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableConceptoMouseClicked(evt);
            }
        });
        scroll.setViewportView(tableConcepto);

        titDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titDatos.setText("Crear tercero");

        lbl1.setText("Id");

        txtDescrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripActionPerformed(evt);
            }
        });

        lbl9.setText("Descripcion");

        btn.setText("Crear");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        btnEliminar.setText("Elminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setEnabled(false);

        lbl10.setText("Estado");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo", " " }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addComponent(txtDescrip)
                    .addComponent(txtId))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableConceptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableConceptoMouseClicked
   int row = tableConcepto.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar una fila válida",
                "Selección",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            btnEliminar.setVisible(true);
            btnEliminar.setFocusable(true);
            btnEliminar.setEnabled(true);
            
            String id = tableConcepto.getValueAt(row, 0).toString();
            String descripcion = tableConcepto.getValueAt(row, 1).toString();
            String estado = tableConcepto.getValueAt(row, 2).toString();

            txtId.setText(id);
            txtDescrip.setText(descripcion != null ? descripcion : "");

            switch (estado.toLowerCase().trim()) {
                case "inactivo" ->
                cmbEstado.setSelectedIndex(0);
                case "activo" ->
                cmbEstado.setSelectedIndex(1);
                default -> {
                    JOptionPane.showMessageDialog(this,
                        "Estado no definido: " + estado
                        + "\nSe establecerá Activo por defecto",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
                    cmbEstado.setSelectedIndex(1);
                }
            }

            btn.putClientProperty(FlatClientProperties.STYLE, Theme.btnSecun + ";" + Theme.h2);
            btn.setText("Actualizar");

            if (controlador != null) {
                controlador.configurarModoActualizacion();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar los datos de la fila seleccionada: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tableConceptoMouseClicked

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed

    }//GEN-LAST:event_btnActionPerformed

    private void txtDescripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed
    public void limpiarFormulario() {
        txtId.setText("");
        txtDescrip.setText("");
        cmbEstado.setSelectedIndex(1);
        btn.setText("Crear");
        btn.putClientProperty(FlatClientProperties.STYLE, Theme.btnPrinci + ";" + Theme.h2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl9;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scroll;
    public javax.swing.JTable tableConcepto;
    private javax.swing.JLabel tit1;
    private javax.swing.JLabel titDatos;
    public javax.swing.JTextField txtDescrip;
    public javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
