/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.CtrlTercero;
import Theme.Paleta;
import Theme.Theme;
import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.JOptionPane;

/**
 *
 * @author lmog2
 */
public class FrmTerceros extends javax.swing.JPanel {

    private CtrlTercero controlador;

    public FrmTerceros() {
        initComponents();
        panelMain.putClientProperty(FlatClientProperties.STYLE, Theme.getPanel());
        interfaz();
    }

    public void setControlador(CtrlTercero controlador) {
        this.controlador = controlador;
    }

    public void interfaz() {

        tit1.putClientProperty(FlatClientProperties.STYLE, Theme.h1);
        titDatos.putClientProperty(FlatClientProperties.STYLE, Theme.h2);
        panelTitulo.putClientProperty(FlatClientProperties.STYLE, Theme.Headerpanel);
        panelDatos.putClientProperty(FlatClientProperties.STYLE, Theme.Headerpanel);
        // Estiliza la tabla
        // Estilo general de la tabla
        tableTerceros.putClientProperty(FlatClientProperties.STYLE,
                "showHorizontalLines:true;"
                + "showVerticalLines:false;"
                + "rowHeight:40;"
                + "intercellSpacing:10,5");

        // Estilo del encabezado de la tabla
        tableTerceros.getTableHeader().putClientProperty(FlatClientProperties.STYLE,
                "hoverBackground:" + "lighten(" + Paleta.getbColorPanel() + ",4%);"
                + "height:40;"
                + "separatorColor:$TableHeader.background;"
                + "font:bold $h4.font");
        lbl1.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        lbl2.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        lbl2.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        lbl3.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        lbl4.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        lbl5.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        lbl6.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        lbl8.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        lbl9.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        lbl10.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        txtId.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        cmbEstado.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        cmbTi.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        txtIdentifi.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        txtRepresentante.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        txtRazonSocial.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        txtDir.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        txtNum1.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        txtNum2.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        txtAObs.putClientProperty(FlatClientProperties.STYLE, Theme.h3);
        txtIdentifi.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ej. 12412421");
        txtRepresentante.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ej. Alberto Perez");
        txtRazonSocial.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ej. Comerca SAS");
        txtNum1.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ej 3027753201");
        txtNum2.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ej 3027753201");
        btn.putClientProperty(FlatClientProperties.STYLE, Theme.btnPrinci + ";" + Theme.h2);
        btnEliminar.putClientProperty(FlatClientProperties.STYLE, Theme.btnTer + ";" + Theme.h2);
        btnEliminar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        tit1 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tableTerceros = new javax.swing.JTable();
        panelDatos = new javax.swing.JPanel();
        titDatos = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        cmbTi = new javax.swing.JComboBox<>();
        txtIdentifi = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        txtRepresentante = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        txtNum1 = new javax.swing.JTextField();
        lbl8 = new javax.swing.JLabel();
        txtNum2 = new javax.swing.JTextField();
        lbl9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAObs = new javax.swing.JTextArea();
        lbl10 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        lbl7 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();

        panelMain.setBackground(new java.awt.Color(204, 204, 255));

        panelTitulo.setBackground(new java.awt.Color(153, 153, 255));

        tit1.setText("Gestion de terceros");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tit1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        tableTerceros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo Id", "Identificacion", "Representatnte", "Rezon social", "Direccion", "Telefono1", "Telefono2", "Observaciones", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableTerceros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTercerosMouseClicked(evt);
            }
        });
        scroll.setViewportView(tableTerceros);

        titDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titDatos.setText("Crear tercero");

        lbl1.setText("Id");

        lbl2.setText("Tipo de identificacion");

        cmbTi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIT", "CC", "CE", "TI", " " }));

        lbl3.setText("Identficacion");

        lbl4.setText("Representante legal");

        lbl5.setText("Razon social");

        lbl6.setText("Direccion");

        txtDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirActionPerformed(evt);
            }
        });

        txtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum1ActionPerformed(evt);
            }
        });

        lbl8.setText("Telefono #1");

        lbl9.setText("Telefono #2");

        txtAObs.setColumns(20);
        txtAObs.setRows(5);
        jScrollPane1.setViewportView(txtAObs);

        lbl10.setText("Observaciones");

        btn.setText("Crear");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        lbl7.setText("Estado");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo", " " }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        btnEliminar.setText("Elminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setEnabled(false);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRepresentante)
                            .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRazonSocial)
                            .addComponent(txtDir)
                            .addComponent(lbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbTi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(txtIdentifi, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelDatosLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))))
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNum1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(lbl8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)
                            .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(lbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentifi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableTercerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTercerosMouseClicked
        int row = tableTerceros.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                "Debe seleccionar una fila válida",
                "Selección",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            btnEliminar.setVisible(true);
            btnEliminar.setFocusable(true);
            btnEliminar.setEnabled(true);
            String code = tableTerceros.getValueAt(row, 0).toString();
            String ti = tableTerceros.getValueAt(row, 1).toString();
            String iden = tableTerceros.getValueAt(row, 2).toString();
            String reprL = tableTerceros.getValueAt(row, 3).toString();
            String razonSoc = tableTerceros.getValueAt(row, 4).toString();
            String dir = tableTerceros.getValueAt(row, 5).toString();
            String tel1 = tableTerceros.getValueAt(row, 6).toString();
            String tel2 = tableTerceros.getValueAt(row, 7).toString();
            String obs = tableTerceros.getValueAt(row, 8).toString();
            String es = tableTerceros.getValueAt(row, 9).toString();

            txtId.setText(code);

            switch (ti.toUpperCase().trim()) {
                case "NIT" ->
                cmbTi.setSelectedIndex(0);
                case "CC" ->
                cmbTi.setSelectedIndex(1);
                case "CE" ->
                cmbTi.setSelectedIndex(2);
                case "TI" ->
                cmbTi.setSelectedIndex(3);
                default -> {
                    JOptionPane.showMessageDialog(this,
                        "Tipo de identificación no válido: " + ti
                        + "\nSe establecerá NIT por defecto",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
                    cmbTi.setSelectedIndex(0); // NIT por defecto
                }
            }

            txtIdentifi.setText(iden != null ? iden : "");
            txtRepresentante.setText(reprL != null ? reprL : "");
            txtRazonSocial.setText(razonSoc != null ? razonSoc : "");
            txtDir.setText(dir != null ? dir : "");
            txtNum1.setText(tel1 != null ? tel1 : "");
            txtNum2.setText(tel2 != null ? tel2 : "");
            txtAObs.setText(obs != null ? obs : "");

            switch (es.toLowerCase().trim()) {
                case "inactivo" ->
                cmbEstado.setSelectedIndex(0);
                case "activo" ->
                cmbEstado.setSelectedIndex(1);
                default -> {
                    JOptionPane.showMessageDialog(this,
                        "Estado no definido: " + es
                        + "\nSe establecerá Activo por defecto",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
                    cmbEstado.setSelectedIndex(1); // Activo por defecto
                }
            }

            btn.putClientProperty(FlatClientProperties.STYLE, Theme.btnSecun + ";" + Theme.h2);
            btn.setText("Actualizar");

            if (controlador != null) {
                controlador.configurarModoActualizacion();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar los datos de la fila seleccionada: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tableTercerosMouseClicked

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed

    }//GEN-LAST:event_btnActionPerformed

    private void txtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum1ActionPerformed

    private void txtDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirActionPerformed
public void limpiarFormulario() {
    txtId.setText("");
    txtIdentifi.setText("");
    txtRepresentante.setText("");
    txtRazonSocial.setText("");
    txtDir.setText("");
    txtNum1.setText("");
    txtNum2.setText("");
    txtAObs.setText("");
    cmbTi.setSelectedIndex(0);
    cmbEstado.setSelectedIndex(1);
    btn.setText("Crear");
    btn.putClientProperty(FlatClientProperties.STYLE, Theme.btnPrinci + ";" + Theme.h2);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JComboBox<String> cmbEstado;
    public javax.swing.JComboBox<String> cmbTi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scroll;
    public javax.swing.JTable tableTerceros;
    private javax.swing.JLabel tit1;
    private javax.swing.JLabel titDatos;
    public javax.swing.JTextArea txtAObs;
    public javax.swing.JTextField txtDir;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtIdentifi;
    public javax.swing.JTextField txtNum1;
    public javax.swing.JTextField txtNum2;
    public javax.swing.JTextField txtRazonSocial;
    public javax.swing.JTextField txtRepresentante;
    // End of variables declaration//GEN-END:variables
}
